In [1]:
import numpy as np
import pandas as pd
import math

from sklearn.metrics import classification_report, confusion_matrix

import acquire
import prepare
from sklearn.linear_model import LogisticRegression
#new import! 


In [2]:
df = acquire.get_titanic_data()
df

Unnamed: 0  passenger_id  survived  pclass     sex   age  sibsp  parch  \
0             0             0         0       3    male  22.0      1      0   
1             1             1         1       1  female  38.0      1      0   
2             2             2         1       3  female  26.0      0      0   
3             3             3         1       1  female  35.0      1      0   
4             4             4         0       3    male  35.0      0      0   
..          ...           ...       ...     ...     ...   ...    ...    ...   
886         886           886         0       2    male  27.0      0      0   
887         887           887         1       1  female  19.0      0      0   
888         888           888         0       3  female   NaN      1      2   
889         889           889         1       1    male  26.0      0      0   
890         890           890         0       3    male  32.0      0      0   

        fare embarked   class deck  embark_town  alone  
0     7.2500        S   Third  NaN  Southampton      0  
1    71.2833        C   First    C    Cherbourg      0  
2     7.9250        S   Third  NaN  Southampton      1  
3    53.1000        S   First    C  Southampton      0  
4     8.0500        S   Third  NaN  Southampton      1  
..       ...      ...     ...  ...          ...    ...  
886  13.0000        S  Second  NaN  Southampton      1  
887  30.0000        S   First    B  Southampton      1  
888  23.4500        S   Third  NaN  Southampton      0  
889  30.0000        C   First    C    Cherbourg      1  
890   7.7500        Q   Third  NaN   Queenstown      1  

[891 rows x 14 columns]

In [3]:
# Create a model that includes only age, fare, and pclass. 
# Does this model perform better than your baseline?
df.survived.value_counts()
df['baseline'] = 0
the_baseline = (df.survived ==  df.baseline).mean()
the_baseline
train_list = []
validate_list = []

In [4]:
df = prepare.prep_titanic(df)
df = df.dropna()
df.age = df.age.dropna()

train, validate, test = prepare.split_data(df, 'survived')
train

logit1 = LogisticRegression()
logit1



X_train = train.loc[: , ['age', 'fare', 'pclass']]
y_train = train.survived


X_validate = validate.loc[: , ['age', 'fare', 'pclass']]
y_validate = validate.survived

X_test = test.loc[: , ['age', 'fare', 'pclass']]
y_test = test.survived

logit1.fit(X_train, y_train)


train_score = logit1.score(X_train, y_train)

validate_score = logit1.score(X_validate, y_validate)

print(train_score)

print(validate_score)

print(logit1.coef_)
train_list.append(train_score)
validate_list.append(validate_score)
## yes

0.6985981308411215
0.6923076923076923
[[-3.88226144e-02  7.89885935e-04 -1.19551966e+00]]


In [5]:
# Include sex in your model as well. 
# Note that you'll need to encode or create a dummy variable of 
# this feature before including it in a model.



In [6]:
df = prepare.prep_titanic(df)
df = df.dropna()
df.age = df.age.dropna()

train, validate, test = prepare.split_data(df, 'survived')
train

logit1 = LogisticRegression()
logit1
train


X_train = train.loc[: , ['age', 'fare', 'pclass','sex_male']]
y_train = train.survived


X_validate = validate.loc[: , ['age', 'fare', 'pclass','sex_male']]
y_validate = validate.survived

X_test = test.loc[: , ['age', 'fare', 'pclass','sex_male']]
y_test = test.survived

logit1.fit(X_train, y_train)


train_score = logit1.score(X_train, y_train)

validate_score = logit1.score(X_validate, y_validate)

print(train_score)

print(validate_score)
train_list.append(train_score)
validate_list.append(validate_score)
print(logit1.coef_)

0.7873831775700935
0.7692307692307693
[[-2.82321768e-02 -5.42189969e-04 -1.12352478e+00 -2.14276835e+00]]


In [7]:
# Try out other combinations of features and models.
df = prepare.prep_titanic(df)
df = df.dropna()
df.age = df.age.dropna()

train, validate, test = prepare.split_data(df, 'survived')
train

logit1 = LogisticRegression()
logit1
train


X_train = train.loc[: , ['sibsp', 'embark_town_Southampton','sex_male']]
y_train = train.survived


X_validate = validate.loc[: , ['sibsp', 'embark_town_Southampton','sex_male']]
y_validate = validate.survived

X_test = test.loc[: , ['sibsp', 'embark_town_Southampton','sex_male']]
y_test = test.survived

logit1.fit(X_train, y_train)


train_score = logit1.score(X_train, y_train)

validate_score = logit1.score(X_validate, y_validate)

print(train_score)

print(validate_score)
train_list.append(train_score)
validate_list.append(validate_score)
print(logit1.coef_)


0.780373831775701
0.7552447552447552
[[-0.33781986 -0.43977024 -2.38733625]]


In [8]:
# Try out other combinations of features and models.
df = prepare.prep_titanic(df)
df = df.dropna()
df.age = df.age.dropna()

train, validate, test = prepare.split_data(df, 'survived')
train

logit1 = LogisticRegression()
logit1



X_train = train.loc[: , ['alone', 'pclass','embark_town_Queenstown','sex_male','sibsp']]
y_train = train.survived


X_validate = validate.loc[: , ['alone', 'pclass','embark_town_Queenstown','sex_male','sibsp']]
y_validate = validate.survived

X_test = test.loc[: , ['alone', 'pclass','embark_town_Queenstown','sex_male','sibsp']]
y_test = test.survived

logit1.fit(X_train, y_train)


train_score = logit1.score(X_train, y_train)

validate_score = logit1.score(X_validate, y_validate)

print(train_score)

print(validate_score)
train_list.append(train_score)
validate_list.append(validate_score)
print(logit1.coef_)


0.7780373831775701
0.7552447552447552
[[-0.53808865 -0.83178463 -0.11888582 -2.26443789 -0.56213152]]


In [19]:
# Use you best 3 models to predict and evaluate on your validate sample.
data = pd.DataFrame({'train':train_list,
                'validate':validate_list})
data['difference'] = data['train'] - data['validate']
data

train  validate  difference
0  0.698598  0.692308    0.006290
1  0.787383  0.769231    0.018152
2  0.780374  0.755245    0.025129
3  0.778037  0.755245    0.022793

In [22]:
# Choose you best model from the validation performation, 
# and evaluate it on the test dataset. How do the performance 
# metrics compare to validate? to train?
df = prepare.prep_titanic(df)
df = df.dropna()
df.age = df.age.dropna()

train, validate, test = prepare.split_data(df, 'survived')
train

logit1 = LogisticRegression()
logit1
train


X_train = train.loc[: , ['age', 'fare', 'pclass','sex_male']]
y_train = train.survived


X_validate = validate.loc[: , ['age', 'fare', 'pclass','sex_male']]
y_validate = validate.survived

X_test = test.loc[: , ['age', 'fare', 'pclass','sex_male']]
y_test = test.survived

logit1.fit(X_train, y_train)


train_score = logit1.score(X_train, y_train)

validate_score = logit1.score(X_validate, y_validate)

test_score = logit1.score(X_test, y_test)

print(train_score)


print(validate_score)

print(test_score)

# print(logit1.coef_)

0.7873831775700935
0.7692307692307693
0.8251748251748252


In [88]:
def titanic_survived_linear_regression(train, validate, test, list_of_columns, the_C = 1):
    logit1 = LogisticRegression(C =the_C)
    logit1
    train


    X_train = train.loc[: , list_of_columns]
    y_train = train.survived


    X_validate = validate.loc[: , list_of_columns]
    y_validate = validate.survived

    X_test = test.loc[: , list_of_columns]
    y_test = test.survived

    logit1.fit(X_train, y_train)


    train_score = logit1.score(X_train, y_train)

    validate_score = logit1.score(X_validate, y_validate)

    test_score = logit1.score(X_test, y_test)
    
    print(train_score)

    print(validate_score)
    
    return train_score, validate_score, test_score

In [64]:
# Bonus1 How do different strategies for handling the 
# missing values in the age column affect model performance?

##changing age to median
df = acquire.get_titanic_data()
df = prepare.prep_titanic(df)

df['age'] = df['age'].replace(np.nan,df['age'].mean())


train, validate, test = prepare.split_data(df, 'survived')
list_of_columns = ['sibsp', 'age', 'embark_town_Southampton','sex_male']


train_score, validate_score, test_score = titanic_survived_linear_regression(train, validate, test, list_of_columns)

0.795880149812734
0.7752808988764045
[[-0.30760706 -0.0101935  -0.53584593 -2.5440529 ]]


In [70]:
# Bonus1 How do different strategies for handling the 
# missing values in the age column affect model performance?


## changing age to 0

df = acquire.get_titanic_data()
df = prepare.prep_titanic(df)

df['age'] = df['age'].replace(np.nan,0)



train, validate, test = prepare.split_data(df, 'survived')
list_of_columns = ['sibsp', 'age', 'embark_town_Southampton','sex_male']


train_score, validate_score, test_score = titanic_survived_linear_regression(train, validate, test, list_of_columns)

0.799625468164794
0.7752808988764045
[[-0.25449545  0.0066839  -0.58153702 -2.55478452]]


In [71]:
df.age.value_counts()

0.00     177
24.00     30
22.00     27
18.00     26
28.00     25
        ... 
36.50      1
55.50      1
0.92       1
23.50      1
74.00      1
Name: age, Length: 89, dtype: int64

In [81]:
# Bonus2: How do different strategies for encoding sex affect model performance?

df = acquire.get_titanic_data()
df = prepare.prep_titanic(df)

df['age'] = df['age'].replace(np.nan,0)



train, validate, test = prepare.split_data(df, 'survived')
list_of_columns = ['sibsp', 'age', 'embark_town_Southampton','sex_male']


train_score, validate_score, test_score = titanic_survived_linear_regression(train, validate, test, list_of_columns)

0.799625468164794
0.7752808988764045
[[-0.25449545  0.0066839  -0.58153702 -2.55478452]]


In [89]:
# Bonus3: scikit-learn's LogisticRegression classifier is actually applying a 
#     regularization penalty to the coefficients by default. 
#     This penalty causes the magnitude of the coefficients in the 
#     resulting model to be smaller than they otherwise would be. 
#     This value can be modified with the C hyper parameter. 
#     Small values of C correspond to a larger penalty, and 
#     large values of C correspond to a smaller penalty.
# Try out the following values for C and note how the coefficients
# and the model's performance on both the dataset it was trained 
# on and on the validate split are affected.

# Bonus2: How do different strategies for encoding sex affect model performance?

df = acquire.get_titanic_data()
df = prepare.prep_titanic(df)

df['age'] = df['age'].replace(np.nan,0)



train, validate, test = prepare.split_data(df, 'survived')
list_of_columns = ['sibsp', 'age', 'embark_town_Southampton','sex_male']

the_c_list = [.01, .1, 1, 10, 100, 1000]
for i in the_c_list:
    print(i)
    train_score, validate_score, test_score = titanic_survived_linear_regression(train, validate, test, list_of_columns, the_C=i)

0.01
0.6385767790262172
0.651685393258427
0.1
0.8052434456928839
0.7752808988764045
1
0.799625468164794
0.7752808988764045
10
0.799625468164794
0.7752808988764045
100
0.799625468164794
0.7752808988764045
1000
0.799625468164794
0.7752808988764045
